# Generated by Django 4.2.8 on 2024-06-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('president', models.CharField(max_length=100)),
                ('vice_president', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='sport',
            field=models.CharField(blank=True, choices=[('Cricket', 'Cricket'), ('Football', 'Football'), ('Tennis', 'Tennis'), ('Badminton', 'Badminton'), ('Volleyball', 'Volleyball'), ('Hockey', 'Hockey'), ('Basketball', 'Basketball'), ('Table Tennis', 'Table Tennis')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
