# Generated by Django 4.2.8 on 2024-05-28 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_date', models.DateTimeField()),
                ('participants', models.ManyToManyField(blank=True, to='users.member')),
            ],
        ),
    ]
