# Generated by Django 4.2.8 on 2024-06-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='event_managers', to='users.member'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='event_participants', to='users.member'),
        ),
    ]
