# Generated by Django 4.2.8 on 2024-06-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_managers_alter_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_sports',
            field=models.BooleanField(default=False),
        ),
    ]
