# Generated by Django 4.2.8 on 2024-06-06 09:36

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content',
            field=markdownfield.models.MarkdownField(blank=True, null=True, rendered_field='content_rendered'),
        ),
        migrations.AddField(
            model_name='event',
            name='content_rendered',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
    ]
